"""add ease factor to learning progress

Revision ID: 28eddd505dc5
Revises: 43f413d8363a
Create Date: 2026-08-31 17:14:02.200674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28eddd505dc5'
down_revision: Union[str, None] = '43f413d8363a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('learning_progress', sa.Column('ease_factor', sa.Float(), server_default='2.5', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('learning_progress', 'ease_factor')
    # ### end Alembic commands ###
