"""add categories table and topic metadata

Revision ID: 345a257932b1
Revises: b128b2f4c90a
Create Date: 2026-08-29 13:56:46.822442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '345a257932b1'
down_revision: Union[str, None] = 'b128b2f4c90a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('topics', sa.Column('category_id', sa.Integer(), nullable=True))
    op.add_column('topics', sa.Column('importance', sa.Integer(), server_default='3', nullable=False))
    op.add_column('topics', sa.Column('active', sa.Boolean(), server_default='true', nullable=False))
    op.create_foreign_key(
        'fk_topics_category_id_categories', 'topics', 'categories', ['category_id'], ['id']
    )
    # Alembic autogenerate does not detect CHECK constraints — added manually.
    op.create_check_constraint(
        'ck_topics_importance_range', 'topics', 'importance BETWEEN 1 AND 5'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_topics_importance_range', 'topics', type_='check')
    op.drop_constraint('fk_topics_category_id_categories', 'topics', type_='foreignkey')
    op.drop_column('topics', 'active')
    op.drop_column('topics', 'importance')
    op.drop_column('topics', 'category_id')
    op.drop_table('categories')
    # ### end Alembic commands ###
