"""add next_review_at to learning_progress

Revision ID: 81a629525629
Revises: 9da721cb4d92
Create Date: 2026-08-31 10:46:14.402573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81a629525629'
down_revision: Union[str, None] = '9da721cb4d92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('learning_progress', sa.Column('next_review_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('learning_progress', 'next_review_at')
    # ### end Alembic commands ###
