"""add classification fields to source_articles

Revision ID: 9da721cb4d92
Revises: 345a257932b1
Create Date: 2026-08-31 08:07:11.300318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '9da721cb4d92'
down_revision: Union[str, None] = '345a257932b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source_articles', sa.Column('classified_category_id', sa.Integer(), nullable=True))
    op.add_column('source_articles', sa.Column('classified_topic_id', sa.Integer(), nullable=True))
    # create_type=False: difficulty_level already exists (questions.difficulty) —
    # must use postgresql.ENUM directly for the flag to take effect via Alembic.
    op.add_column(
        'source_articles',
        sa.Column(
            'classified_difficulty',
            postgresql.ENUM('BEGINNER', 'INTERMEDIATE', 'ADVANCED', name='difficulty_level', create_type=False),
            nullable=True,
        ),
    )
    op.add_column('source_articles', sa.Column('relevance_score', sa.Integer(), nullable=True))
    op.add_column('source_articles', sa.Column('classified_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(
        'fk_source_articles_classified_topic_id_topics',
        'source_articles', 'topics', ['classified_topic_id'], ['id'],
    )
    op.create_foreign_key(
        'fk_source_articles_classified_category_id_categories',
        'source_articles', 'categories', ['classified_category_id'], ['id'],
    )
    # Alembic autogenerate does not detect CHECK constraints — added manually.
    op.create_check_constraint(
        'ck_source_articles_relevance_range', 'source_articles', 'relevance_score BETWEEN 1 AND 5'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_source_articles_relevance_range', 'source_articles', type_='check')
    op.drop_constraint(
        'fk_source_articles_classified_category_id_categories', 'source_articles', type_='foreignkey'
    )
    op.drop_constraint(
        'fk_source_articles_classified_topic_id_topics', 'source_articles', type_='foreignkey'
    )
    op.drop_column('source_articles', 'classified_at')
    op.drop_column('source_articles', 'relevance_score')
    op.drop_column('source_articles', 'classified_difficulty')
    op.drop_column('source_articles', 'classified_topic_id')
    op.drop_column('source_articles', 'classified_category_id')
    # ### end Alembic commands ###
