"""add source_articles table

Revision ID: 9e73e98a7a0c
Revises: db0aaa589326
Create Date: 2026-08-29 11:40:22.329240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e73e98a7a0c'
down_revision: Union[str, None] = 'db0aaa589326'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_name', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('tags', sa.String(length=500), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_name', 'external_id', name='uq_source_articles_source_external_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('source_articles')
    # ### end Alembic commands ###
