"""add ai_drafts table and question source_draft_id

Revision ID: b128b2f4c90a
Revises: 9e73e98a7a0c
Create Date: 2026-08-29 13:17:02.963476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'b128b2f4c90a'
down_revision: Union[str, None] = '9e73e98a7a0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_article_id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('simple_explanation', sa.Text(), nullable=False),
    sa.Column('real_world_example', sa.Text(), nullable=False),
    sa.Column('business_relevance', sa.Text(), nullable=False),
    # create_type=False: this enum type already exists (created for questions.difficulty
    # in an earlier migration) — reused here, not redefined. Must use postgresql.ENUM
    # directly (not the generic sa.Enum) for create_type=False to actually take effect
    # through Alembic's op.create_table.
    sa.Column(
        'difficulty',
        postgresql.ENUM('BEGINNER', 'INTERMEDIATE', 'ADVANCED', name='difficulty_level', create_type=False),
        nullable=False,
    ),
    sa.Column('keywords', sa.String(length=255), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('GENERATED', 'APPROVED', 'REJECTED', name='draft_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_article_id'], ['source_articles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('questions', sa.Column('source_draft_id', sa.Integer(), nullable=True))
    op.create_unique_constraint('uq_questions_source_draft_id', 'questions', ['source_draft_id'])
    op.create_foreign_key(
        'fk_questions_source_draft_id_ai_drafts', 'questions', 'ai_drafts', ['source_draft_id'], ['id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_questions_source_draft_id_ai_drafts', 'questions', type_='foreignkey')
    op.drop_constraint('uq_questions_source_draft_id', 'questions', type_='unique')
    op.drop_column('questions', 'source_draft_id')
    op.drop_table('ai_drafts')
    # difficulty_level is NOT dropped here — it's still used by the questions table.
    sa.Enum(name='draft_status').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
